# Generated by Django 5.1.4 on 2025-01-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='email@exemplo.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nome',
            field=models.CharField(default='Nome Padrão', max_length=255),
            preserve_default=False,
        ),
    ]
